#!/bin/sh

# Copyright(C) 2015 Nicolas Roudaire http://www.nikrou.net
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301 USA.

# Fill path to your letsencrypt installation and fill your email
# Fill path to your certificate (PEM file)
# Put that file in your /etc/cron.daily directory and make it executable.


DAY_LIMIT=30
TIMESTAMP_LIMIT=$(($DAY_LIMIT*86400))

OPENSSL=/usr/bin/openssl
SSL_PEM=PATH_TO_PEM_CERTIFICATE

MAIL=/usr/bin/mail -s "[ssl] Update" YOUR_EMAIL@YOUR.DOMAIN

PATH_LETSENCRYPT=PATH_TO_LETSENCRYPT_INSTALLATION

if $OPENSSL x509 -checkend $TIMESTAMP_LIMIT -noout -in $SSL_PEM
then
    echo "Certificate is valid for more than $DAY_LIMIT days. Do not update." | $MAIL
else
    cd $(PATH_LETSENCRYPT)  && ./letsencrypt-auto -c /etc/letsencrypt/cli.ini
    if [ $? -ne 0 ];then
	echo "Something goes wrong. Cannot update ssl certificate. Need to validate it manually" | $MAIL
    else
        echo "Certificate has been updated" | $MAIL
    fi
fi


exit 0
